# Generated by Django 4.2.11 on 2024-05-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_post', '0003_comment_imagepost_date_created_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='FK_Like_Comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_post.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='FK_Like_Post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_post.imagepost'),
        ),
    ]
